# ------------------------------------------------------------------------------
# file        : graphs_report.R
# description : generates graphics for report and for various slides
# ------------------------------------------------------------------------------

# -- packages ------------------------------------------------------------------
library(ggplot2)
library(compoisson)
library(magrittr)
library(tikzDevice)

# little function to create the names of files
prefix  <- "~/documents/master/m2/stage/report/img/"
paf <- function(string) paste0(prefix, string)

# colorblind friendly palette
cb_palette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442",
                "#0072B2", "#D55E00", "#CC79A7")


# ------------------------------------------------------------------------------
# graphics for report
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# verifications of estimations

# get the data generated by 'verif_ab.R'
load('data/generated/data_verif.RData')


# -- estimations Vs observed + bootstraps --------------------------------------
aa <- cor_all[cor_all$observed != 0,]

aa$method <- factor(aa$method,
                    levels = unique(aa$method))
colnames(tab_boot)[length(tab_boot)] <- "method"

tab_boot$method <- unlist(lapply(tab_boot$method, function(old, new)
                                 match.arg(old, new), new = unique(aa$method)))

p <-
  ggplot(aa, aes(x = log(estimate), y = log(observed))) +
  geom_point(size = 0.8, shape = 1, position = "jitter") +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  geom_line(data = tab_boot, aes(x = x, y = moy),
            colour = "red") +
  geom_ribbon(data = tab_boot, aes(ymin = icinf, ymax = icsup, x = x),
              inherit.aes = FALSE,
              fill = "red",
              alpha = 0.3) +
  facet_wrap(~ method, scales = "fixed") +
  xlab("log(Abondance estimée)") +
  ylab("log(Abondance observée)") +
  theme_bw() +
  labs(colour = "Estimation") +
  guides(colour = guide_legend(override.aes = list(size = 3, shape = 19))) +
  theme(strip.background = element_rect(fill = "white", size = rel(1))) +
  theme(strip.text = element_text(size = rel(1.1))) +
  theme(axis.title = element_text(size = rel(1.2))) +
  theme(axis.text = element_text(size = rel(1))) +
  scale_colour_manual(values = cb_palette)

pdf(paf("estimations_log.pdf"), height = 4.4, width = 6)
plot(p)
dev.off()


# -- variations of errors ------------------------------------------------------

orig <- transposed[["orig"]]
observed_ab <- apply(orig[,4:length(orig)], 1, sum)
observed_ab <- observed_ab[observed_ab != 0]

# error on the model
estim <- cor_gpoisson[cor_gpoisson$observed != 0,]
estim_error <- abs(estim$observed - estim$estimate)
estim_error[estim_error < 1e-04] <- 0

tab <- cbind.data.frame(observed_ab, estim_error)
tab <- tab[tab$estim_error != 0,]

p <-
  ggplot(tab, aes(x = log(observed_ab), y = log(estim_error))) +
  geom_point(size = 1.2, shape = 1, position = "jitter") +
  geom_abline(slope = 1, intercept = 0, col = "red", size = 0.7) +
  theme_bw() +
  theme(axis.title = element_text(size = rel(1.2))) +
  theme(axis.text = element_text(size = rel(1))) +
  xlab("Abondance observée (log)") +
  ylab("Erreur sur l'estimation (log)")

pdf(paf("erreurs.pdf"), height = 3.2, width = 3.2)
plot(p)
dev.off()


# -- dataset description -------------------------------------------------------
# histogram
tab <- transposed[["orig"]]
tab <- tab[rowSums(tab[,4:length(tab)]) != 0,]
b <- apply(tab[,4:length(tab)], 1, sum)

binsize <- diff(range(b)) / 20
p <- ggplot(data.frame(x = b), aes(x = x)) +
  geom_rect(aes(xmin = quantile(x, 0.025), xmax = quantile(x, 0.975),
                ymin = -Inf, ymax = Inf), fill = "lightslategrey", alpha = 0.02) +
  geom_histogram(binwidth = binsize, fill = "white", col = "black") +
  geom_vline(aes(xintercept = median(x)), col = "red", linetype = "dotted") +
  geom_vline(aes(xintercept = quantile(x, 0.025)), col = "darkgreen", linetype = "dashed") +
  geom_vline(aes(xintercept = quantile(x, 0.975)), col = "darkgreen", linetype = "dashed") +
  xlab("Abondance observée") +
  ylab("Fréquence") +
  theme_bw() +
  theme(axis.title = element_text(size = rel(1.2))) +
  theme(axis.text = element_text(size = rel(1))) #+

pdf(paf("description1.pdf"), height = 2.4, width = 2.8)
plot(p)
dev.off()

# variation of errors
bb <- data.frame(t(apply(tab[,4:length(tab)], 1, function(x) cbind(sum(x), var(x)))))
colnames(bb) <- c("sum", "sd")

p <- ggplot(bb, aes(x = log(sum), y = log(sd))) +
  geom_point(size = 1.2, shape = 1, position = "jitter") +
  geom_abline(slope = 1, intercept = 0, col = "red", size = 0.7, linetype = "dashed") +
  xlab("log(Abondance observée)") +
  ylab("log(Variance observé)") +
  theme_bw() +
  theme(axis.title = element_text(size = rel(1.2))) +
  theme(axis.text = element_text(size = rel(1))) #+

pdf(paf("description2.pdf"), height = 2.4, width = 2.8)
plot(p)
dev.off()


# -- errors on estimations -----------------------------------------------------
# graph to show mean error on estimations + confidence intervals

p <-
  ggplot(err_sum, aes(x = mean, y = method)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = ci_inf, xmax = ci_sup), height = 0.2) +
  geom_vline(xintercept = 0, lty = "dotted") +
  xlab("Erreur moyenne") +
  ylab("") +
  theme_bw() +
  theme(panel.grid    = element_blank(),
        axis.line.x   = element_line(size = 0.5, colour = "black"),
        axis.text.x   = element_text(size = 9),
        axis.ticks.y  = element_blank(),
        axis.title    = element_text(size = 10),
        panel.border  = element_blank())

pdf(paf("mean_errors.pdf"), height = 2.5, width = 5)
plot(p)
dev.off()


# -- min number of quadras -----------------------------------------------------

p <- boot_quadras %>%
  group_by(nqd) %>%
  summarise(errmean = mean(err),
            errinf  = quantile(err, 0.025),
            errsup  = quantile(err, 0.975)) %>%
  ggplot(aes(x = nqd, y = errmean)) +
  geom_point() +
  geom_errorbar(aes(ymin = errinf, ymax = errsup)) +
  geom_hline(aes(yintercept = 40), col = 'red', linetype = "dashed") +
  # geom_hline(yintercept = 40, linetype = "dashed", col = "red") +
  theme_bw()

pdf(paf("min_quadras.pdf"), height = 3.2, width = 3.2)
plot(p)
dev.off()
